---
- firewalld:
    immediate: yes
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
  - 8300
  - 8301
  - 8302
  - 8400
  - 8500
  - 8600


- firewalld:
    immediate: yes
    port: "{{ item }}/udp"
    permanent: true
    state: enabled
  with_items:
  - 8301
  - 8302
  - 8600